import { registerButtonsBlock } from '@/blocks/buttons/register';
import { registerHeaderBlock } from '@/blocks/header/register';
import { registerListBlock } from '@/blocks/list/register';
import { registerMediaBlock } from '@/blocks/media/register';
import { registerNumberBlock } from '@/blocks/number/register';
import { registerNumbersBlock } from '@/blocks/numbers/register';
import { registerQueryBlock } from '@/blocks/query/register';
import { registerReviewsBlock } from '@/blocks/reviews/register';
import { registerSectionBlock } from '@/blocks/section/register';
import { registerSubtitleBlock } from '@/blocks/subtitle/register';
import { registerTextBlock } from '@/blocks/text/register';
import { registerTitleBlock } from '@/blocks/title/register';
import '@/extensions/button-icon';

registerSectionBlock();
registerHeaderBlock();
registerSubtitleBlock();
registerTitleBlock();
registerTextBlock();
registerNumbersBlock();
registerNumberBlock();
registerButtonsBlock();
registerMediaBlock();
registerListBlock();
registerQueryBlock();
registerReviewsBlock();
